version: '3'

services:
#  api-docs: 
#    container_name: tools-apidoc
#    build:
#      context: ./tools/apidoc
#    volumes:
#      - /home/d.rusakov/symfony-api:/project-root

  api-server-prod:
    container_name: tools-api-server-prod
    image: nexus-docker.andersenlab.dev/polygon-backend:prod
    ports:
      - "1100:80"
      - "9001:9001"
    volumes:
        - /opt/prod/logs:/var/log/nginx
    depends-on:
      - symfony-api-prod
    networks:
      - backend-prod

  symfony-api-prod:
    container_name: symfony-api-prod
    image: nexus-docker.andersenlab.dev/polygon-backend:symfony-prod
    volumes:
      - /home/${DOCKER_USER}/.composer:/home/${DOCKER_USER}/.composer
    ports:
      - "9000:9000"
    networks:
      - backend-prod
 
 # mailer service
  mailer-prod:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    logging:
        driver: "none"
    networks:
      - backend-prod
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  backend-prod:
    driver: bridge
