services:
  App\Src\DataFixtures\:
    resource: "%kernel.project_dir%/src/DataFixtures/RegistrationFixtures.php"
    tags:
      - {"name": "doctrine.fixture.orm"}
  App\Service\MoneyTransferService:
    public: TRUE
