<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DoubleValidationTest extends WebTestCase
{
    private $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    /**
     * @dataProvider userDataProvider
     */
    public function testEmailRegistration(array $data, int $expectedCode): void
    {
        $this->client->jsonRequest('POST', 'api/auth/sendemail', $data);
        $response = $this->client->getResponse();

        $this->assertSame(400, $response->getStatusCode());
        $responseData = json_decode($response->getContent());
        $this->assertSame(false, $responseData->success);
        $this->assertSame('A user with this email has already been registered in the system. Please call the number +7 XXX XXXX XXXX or contact the nearest bank office.', $responseData->body->message);
    }

    public function userDataProvider()
    {
        return [
            [
                [
                    'email' => 'alex1@aa.com',
                ],
                400,
            ],
        ];
    }
}
