<?php

namespace App\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class WrongSessionIdTest extends WebTestCase
{
    private $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    /**
     * @dataProvider userDataProvider
     */
    public function testSessionCodeRegistration(array $data, int $expectedCode): void
    {
        $this->client->jsonRequest('POST', 'api/auth/code', $data);
        $response = $this->client->getResponse();

        $this->assertSame($expectedCode, $response->getStatusCode());
        $responseData = json_decode($response->getContent());
        $this->assertSame(false, $responseData->success);
    }

    /**
     * @dataProvider userDataPasswordProvider
     */
    public function testSessionPasswordRegistration(array $data, int $expectedCode): void
    {
        $this->client->jsonRequest('POST', 'api/auth/password', $data);
        $response = $this->client->getResponse();

        $this->assertSame($expectedCode, $response->getStatusCode());
        $responseData = json_decode($response->getContent());
        $this->assertSame(false, $responseData->success);
    }

    public function userDataProvider()
    {
        return [
            [
                [
                    'code' => '',
                ],
                400
            ]
        ];
    }

    public function userDataPasswordProvider()
    {
        return [
            [
                [
                    'password' => '',
                ],
                400
            ]
        ];
    }
}
