<?php

namespace ContainerAeEyAl0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchCodesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MatchCodesController' shared autowired service.
     *
     * @return \App\Controller\MatchCodesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MatchCodesController.php';

        $container->services['App\\Controller\\MatchCodesController'] = $instance = new \App\Controller\MatchCodesController(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\MatchCodesController', $container));

        return $instance;
    }
}
