version: '3'

services:
#  api-docs: 
#    container_name: tools-apidoc
#    build:
#      context: ./tools/apidoc
#    volumes:
#      - /home/d.rusakov/symfony-api:/project-root

  api-server-dev-new:
    container_name: $API_SERVER_CONTAINER_NAME-$CI_COMMIT_BRANCH
    image: $AND_DOCKER_REGISTRY_NAME/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
    ports:
      - "1101:80"
      - "9002:9001"
    volumes:
        - /opt/prod/logs:/var/log/nginx
    networks:
      - backend

  symfony-api-dev-new:
    environment:
      - DOCKER_USER="a.fetissov"
    container_name: $SYMFONY_CONTAINER_NAME-$CI_COMMIT_BRANCH
    image: $AND_DOCKER_REGISTRY_NAME/$CI_PROJECT_NAME:symfony-$CI_COMMIT_BRANCH
    volumes:
      - /home/${DOCKER_USER}/.composer:/home/${DOCKER_USER}/.composer
    networks:
      - backend
 
 # mailer service
  # mailer-dev:
  #   container_name: mailhog
  #   image: mailhog/mailhog
  #   restart: always
  #   logging:
  #       driver: "none"
  #   networks:
  #     - backend
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"

networks:
  backend:
    driver: bridge
