version: '3'

services:
#  api-docs: 
#    container_name: tools-apidoc
#    build:
#      context: ./tools/apidoc
#    volumes:
#      - /home/d.rusakov/symfony-api:/project-root

  api-server-dev:
    container_name: tools-api-server
    image: nexus-docker.andersenlab.dev/polygon-backend:dev
    ports:
      - "1100:80"
      - "9001:9001"
    volumes:
        - /opt/prod/logs:/var/log/nginx
    networks:
      - backend

  symfony-api-dev:
    environment:
      - DOCKER_USER="a.fetissov"
    container_name: symfony-api
    image: nexus-docker.andersenlab.dev/polygon-backend:symfony-dev
    volumes:
      - /home/${DOCKER_USER}/.composer:/home/${DOCKER_USER}/.composer
    networks:
      - backend
 
 # mailer service
  # mailer-dev:
  #   container_name: mailhog
  #   image: mailhog/mailhog
  #   restart: always
  #   logging:
  #       driver: "none"
  #   networks:
  #     - backend
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"

networks:
  backend:
    driver: bridge
