<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXG45GVv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXG45GVv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXG45GVv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXG45GVv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXG45GVv\App_KernelDevDebugContainer([
    'container.build_hash' => 'XG45GVv',
    'container.build_id' => 'e0e6d19a',
    'container.build_time' => 1661783140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXG45GVv');
