<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLlKehtE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLlKehtE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLlKehtE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLlKehtE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLlKehtE\App_KernelDevDebugContainer([
    'container.build_hash' => 'LlKehtE',
    'container.build_id' => '813a63e4',
    'container.build_time' => 1662035804,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLlKehtE');
