<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD02IjP9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD02IjP9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD02IjP9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD02IjP9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD02IjP9\App_KernelDevDebugContainer([
    'container.build_hash' => 'D02IjP9',
    'container.build_id' => 'ac329fc3',
    'container.build_time' => 1663154093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD02IjP9');
