<?php

namespace ContainerXG45GVv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Factory\UserFactory' shared autowired service.
     *
     * @return \App\Factory\UserFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/ModelFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/UserFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/FileFactory.php';

        return $container->privates['App\\Factory\\UserFactory'] = new \App\Factory\UserFactory(($container->privates['App\\Factory\\FileFactory'] ?? ($container->privates['App\\Factory\\FileFactory'] = new \App\Factory\FileFactory())), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
